name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 80
  IS_PR_CHECK: false

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrices.outputs.matrix }}
      delete: ${{ steps.generate-matrices.outputs.delete }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last successful CI commit
        uses: nrwl/nx-set-shas@v4
        with:
          fallback-sha: 4b825dc642cb6eb9a060e54bf8d69288fbee4904

      - id: generate-matrices
        name: Create output matrices
        run: |
          python ./.github/scripts/generate-build-matrices.py "4b825dc642cb6eb9a060e54bf8d69288fbee4904" Release

  build:
    name: Build extensions (${{ matrix.chunk.number }})
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: ${{ toJson(fromJson(needs.prepare.outputs.matrix).chunk) != '[]' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ matrix.chunk.number > 1 }}

      - name: Prepare signing key
        run: |
          keytool -genkey -v -keystore signingkey.jks -alias key0 -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Unknown" -storetype JKS

      - name: Build extensions (${{ matrix.chunk.number }})
        env:
          MODULES: ${{ join(matrix.chunk.modules, ' ') }}
        run: |
          ./gradlew $MODULES -Pandroid.injected.signing.store.file=$(pwd)/signingkey.jks -Pandroid.injected.signing.store.password=123456 -Pandroid.injected.signing.key.alias=key0 -Pandroid.injected.signing.key.password=123456

      - name: Upload APKs (${{ matrix.chunk.number }})
        uses: actions/upload-artifact@v4
        with:
          name: "individual-apks-${{ matrix.chunk.number }}"
          path: "**/*.apk"
          retention-days: 1

      - name: Clean up CI files
        run: rm signingkey.jks

  publish:
    name: Publish extension repo
    needs: [prepare, build]
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          path: ~/apk-artifacts

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Create repo artifacts
        run: |
          cd main
          python ./.github/scripts/move-built-apks.py
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/keiyoushi/extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "repo/apk" "output.json" "tmp"
          python ./.github/scripts/create-repo.py

      - name: Checkout repo branch
        uses: actions/checkout@v4
        with:
          ref: repo
          path: repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy APKs and deploy repo
        env:
          DELETE: ${{ needs.prepare.outputs.delete }}
        run: |
          mkdir -p repo/apk
          find ~/apk-artifacts -name "*.apk" -exec cp {} repo/apk/ \;
          cp main/repo/index.min.json repo/index.min.json || true
          cp main/repo/index.json repo/index.json || true
          cp main/repo/index.pb repo/index.pb || true
          cp -r main/repo/icon repo/icon || true
          cd repo
          rm -f .gitignore
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -f .
          git commit -m "Update extensions repo" || echo "Nothing to commit"
          git push
